Remove Section 3.9: Reduced Complexity Signaling
w3c/webrtc-nv-use-cases pull request #112
Opened 2023-06-22 20:00 UTC by aboba

Fixes https://github.com/w3c/webrtc-nv-use-cases/issues/109

***
<a href="https://pr-preview.s3.amazonaws.com/aboba/webrtc-nv-use-cases/pull/112.html" title="Last updated on Jun 29, 2023, 2:37 PM UTC (bc2ed07)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-nv-use-cases/112/29c2769...aboba:bc2ed07.html" title="Last updated on Jun 29, 2023, 2:37 PM UTC (bc2ed07)">Diff</a>

2023-06-27 18:09 UTC, aboba commented
This PR was discussed at the June 27 WEBRTC WG Virtual Interim. There were no objections to removing the use case.

2023-06-29 14:20 UTC, youennf approved these changes

2023-06-29 14:22 UTC, aboba commented
Wrong section. The PR is removing Section 3.4, not 3.9!

2023-06-29 14:24 UTC, jan-ivar requested changes
wrong section

2023-07-06 14:36 UTC, jan-ivar approved these changes

2023-07-06 14:37 UTC, merged